export const S = {
  app: {
    minHeight: "100vh",
    background: "#060912",
    color: "#e8eaf6",
    fontFamily: "'Syne', 'Space Grotesk', sans-serif",
    position: "relative",
    overflow: "hidden",
  },
  nav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "20px 40px",
    borderBottom: "1px solid #1a1f35",
    backdropFilter: "blur(20px)",
    background: "rgba(6,9,18,0.8)",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 22,
    fontWeight: 800,
    letterSpacing: -0.5,
    color: "#fff",
  },
  logoAccent: { color: "#3b82f6" },
  navTabs: { display: "flex", gap: 4 },
  navTab: (active) => ({
    padding: "8px 18px",
    borderRadius: 8,
    border: "none",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    transition: "all 0.2s",
    background: active ? "#3b82f6" : "transparent",
    color: active ? "#fff" : "#8892b0",
  }),
  hero: {
    textAlign: "center",
    padding: "80px 40px 40px",
    position: "relative",
  },
  heroTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "#3b82f610",
    border: "1px solid #3b82f630",
    borderRadius: 20,
    padding: "4px 14px",
    fontSize: 12,
    color: "#60a5fa",
    marginBottom: 20,
    fontWeight: 600,
    letterSpacing: 0.5,
  },
  heroTitle: {
    fontSize: "clamp(36px, 5vw, 64px)",
    fontWeight: 900,
    lineHeight: 1.1,
    marginBottom: 16,
    background: "linear-gradient(135deg, #fff 0%, #93c5fd 50%, #6366f1 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  heroSub: {
    fontSize: 17,
    color: "#64748b",
    maxWidth: 560,
    margin: "0 auto 40px",
    lineHeight: 1.6,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "380px 1fr",
    gap: 24,
    padding: "0 40px 40px",
    maxWidth: 1400,
    margin: "0 auto",
  },
  card: {
    background: "rgba(15,20,40,0.8)",
    border: "1px solid #1e2a4a",
    borderRadius: 16,
    padding: 24,
    backdropFilter: "blur(20px)",
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 20,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  label: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: 600,
    marginBottom: 6,
    display: "block",
    letterSpacing: 0.5,
  },
  input: {
    width: "100%",
    background: "#0d1224",
    border: "1px solid #1e2a4a",
    borderRadius: 10,
    padding: "10px 14px",
    color: "#e8eaf6",
    fontSize: 14,
    outline: "none",
    transition: "border-color 0.2s",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  select: {
    width: "100%",
    background: "#0d1224",
    border: "1px solid #1e2a4a",
    borderRadius: 10,
    padding: "10px 14px",
    color: "#e8eaf6",
    fontSize: 14,
    outline: "none",
    cursor: "pointer",
    boxSizing: "border-box",
  },
  btn: (variant = "primary") => ({
    padding: "12px 24px",
    borderRadius: 10,
    border: "none",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 700,
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    background: variant === "primary" ? "linear-gradient(135deg, #3b82f6, #6366f1)" : "rgba(59,130,246,0.1)",
    color: variant === "primary" ? "#fff" : "#3b82f6",
    border: variant === "secondary" ? "1px solid #3b82f620" : "none",
    width: "100%",
  }),
  resultCard: (rank) => ({
    background: rank === 0 ? "linear-gradient(135deg, rgba(59,130,246,0.12), rgba(99,102,241,0.08))" : "rgba(15,20,40,0.6)",
    border: rank === 0 ? "1px solid #3b82f640" : "1px solid #1e2a4a",
    borderRadius: 14,
    padding: 20,
    marginBottom: 12,
    position: "relative",
    transition: "transform 0.2s",
    cursor: "pointer",
  }),
  metric: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  metricVal: {
    fontSize: 20,
    fontWeight: 800,
    color: "#fff",
    lineHeight: 1,
  },
  metricLabel: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: 500,
  },
  tag: (color) => ({
    background: color + "20",
    color: color,
    border: `1px solid ${color}40`,
    borderRadius: 6,
    padding: "2px 8px",
    fontSize: 11,
    fontWeight: 600,
  }),
  scoreBar: (score) => ({
    height: 4,
    borderRadius: 2,
    background: `linear-gradient(90deg, #3b82f6 ${score}%, #1e2a4a ${score}%)`,
    marginTop: 8,
  }),
  codeBlock: {
    background: "#080d1a",
    border: "1px solid #1e2a4a",
    borderRadius: 12,
    padding: 20,
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    fontSize: 12,
    color: "#7dd3fc",
    overflow: "auto",
    maxHeight: 400,
    lineHeight: 1.7,
    position: "relative",
    whiteSpace: "pre",
  },
  chatFab: {
    position: "fixed",
    bottom: 30,
    right: 30,
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #3b82f6, #6366f1)",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    boxShadow: "0 8px 32px rgba(59,130,246,0.4)",
    zIndex: 200,
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  chatWindow: (open) => ({
    position: "fixed",
    bottom: 96,
    right: 30,
    width: 380,
    height: open ? 520 : 0,
    background: "#0a0f1e",
    border: "1px solid #1e2a4a",
    borderRadius: 18,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    transition: "height 0.3s cubic-bezier(0.4,0,0.2,1)",
    zIndex: 200,
    boxShadow: "0 24px 64px rgba(0,0,0,0.6)",
  }),
  chatHeader: {
    padding: "16px 20px",
    background: "linear-gradient(135deg, #3b82f620, #6366f110)",
    borderBottom: "1px solid #1e2a4a",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  chatMessages: {
    flex: 1,
    overflowY: "auto",
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  chatMsg: (role) => ({
    maxWidth: "82%",
    alignSelf: role === "user" ? "flex-end" : "flex-start",
    background: role === "user" ? "linear-gradient(135deg, #3b82f6, #6366f1)" : "#131929",
    color: "#e8eaf6",
    borderRadius: role === "user" ? "16px 16px 4px 16px" : "16px 16px 16px 4px",
    padding: "10px 14px",
    fontSize: 13,
    lineHeight: 1.5,
    border: role === "assistant" ? "1px solid #1e2a4a" : "none",
    whiteSpace: "pre-wrap",
  }),
  chatInput: {
    display: "flex",
    gap: 8,
    padding: 12,
    borderTop: "1px solid #1e2a4a",
    background: "#060912",
  },
  chatField: {
    flex: 1,
    background: "#0d1224",
    border: "1px solid #1e2a4a",
    borderRadius: 10,
    padding: "8px 14px",
    color: "#e8eaf6",
    fontSize: 13,
    outline: "none",
    resize: "none",
    fontFamily: "inherit",
  },
  chatSend: {
    width: 38,
    height: 38,
    borderRadius: 10,
    background: "linear-gradient(135deg, #3b82f6, #6366f1)",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    flexShrink: 0,
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 12,
    marginBottom: 20,
  },
  statCard: {
    background: "#0d1224",
    border: "1px solid #1e2a4a",
    borderRadius: 12,
    padding: 16,
    textAlign: "center",
  },
};
